apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-gateway
  namespace: playground
spec:
  hosts:
  - "*"
  gateways:
  - default-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend.playground.svc.cluster.local
