apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: playground
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: gcr.io/hijup-prod/github-hijup-playground-istio-canary-release-frontend:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
