apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: playground
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: frontend
